### ISSUE TITLE
Update Our Team

### ISSUE THREAD

**Issue by Nithin-Valiyaveedu** [Uyadav207/pentamorphs#6]
Update our team section with the following details:

Team Members:

Member 1: 

Name: **Nithin Valiyaveedu**
Role: 
Photo: https://drive.google.com/file/d/1j2t0KOimtaqIVzf7S8STtwuzWZ2zrFP-/view?usp=sharing
Portfolio: https://3d-portfolio-steel-sigma.vercel.app/
LinkedIn: https://www.linkedin.com/in/nithin-valiyaveedu/
Github: https://github.com/Nithin-Valiyaveedu

Member 2: 

Name: **Chaitali Satishkumar Tamboliya**
Role: 
Photo: https://drive.google.com/file/d/10orVE3yzgExrnmScVGmGYk0a9ddSjcNl/view?usp=sharing
Portfolio: N/A
LinkedIn: https://www.linkedin.com/in/chaitali-tamboliya/
Github: https://github.com/chaitali-1805/

Member 3: 

Name: **Utkarsh Yadav**
Role: 
Photo: https://drive.google.com/file/d/1L-i8afpkw8yPLbvblXj0VErn4ICYIxGn/view?usp=sharing
linkedin: https://www.linkedin.com/in/yadavutkarsh
Portfolio: https://utkarshyadav.vercel.app/
Github: https://github.com/Uyadav207

Member 4:
Name:  **Sindhura Shivaprasad**
Role: 
Photo: https://drive.google.com/file/d/1C3ECX4i2Dbw2dR27ke8rynHDlCfb6qqK/view?usp=sharing
LinkedIn: https://www.linkedin.com/in/sindhura-s-9a55731b4/
Github:https://github.com/Sindhura492
Portfolio:NA

**Comment by Nithin-Valiyaveedu** [comment]
Others please update your details/photos separately as a PR.

**Comment by kadamshweta11** [comment]
For Final Changes
